name = "mari0_se"
default_targets = [
	"appimage",
	"win32",
	"win64",
	"macos",
]
build_directory = "makelove-build"
icon_file = "graphics/iconbig.png"

love_files = [
	"::git-ls-tree::",
	"-*/.*",
	"-*/makelove*",
	"-*/Makefile*",
	"-local.lua",
]

[windows.exe_metadata]
ProductName = "Mari0"
CompanyName = "StabYourself.net"
LegalCopyright = "Copyright © 2006-2023 Maurice Guégan"

[linux.desktop_file_metadata]
Name = "Mari0"

[macos.app_metadata]
CFBundleName = "Mari0"
CFBundleIdentifier = "net.stabyourself"
NSHumanReadableCopyright = "Copyright © 2006-2023 Maurice Guégan"
